import { Spacing, Typography, useColors } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';

export const createModalStyles = (colors: ReturnType<typeof useColors>) => StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
  },
  titleSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Spacing.modal.titlePadding,
    paddingHorizontal: Spacing.modal.titlePaddingHorizontal,
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  title: {
    flex: 1,
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
  },
  stepSlide: {
    alignItems: 'center',
    backgroundColor: Platform.OS === 'android' ? colors.cardBackground : undefined,
  },
  mediaContainer: {
    height: Platform.OS === 'android' ? 120 : Spacing.modal.mediaContainerHeight,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    width: '100%',
    paddingBottom: Platform.OS === 'android' ? 20 : 0,
  },
  contentSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingTop: Platform.OS === 'android' ? Spacing.l : Spacing.l,
    paddingBottom: Platform.OS === 'android' ? 0 : Spacing.l,
    paddingHorizontal: Spacing.modal.contentPaddingHorizontal,
    gap: Platform.OS === 'android' ? 0 : Spacing.modal.contentGap,
    backgroundColor: colors.cardBackground,
    width: '100%',
    height: Platform.OS === 'android' ? 'auto' : 'auto',
  },
  stepContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: Platform.OS === 'android' ? Spacing.s : Spacing.modal.stepTitleGap,
    width: '100%',
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.stepTitleGap,
    width: '100%',
  },
  numberCircle: {
    width: Spacing.modal.numberCircleSize,
    height: Spacing.modal.numberCircleSize,
    borderRadius: Spacing.modal.numberCircleSize / 2,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  numberText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.body,
    color: colors.buttonText,
  },
  stepTitle: {
    flex: 1,
    fontFamily: Typography.fontFamily.bold,
    fontSize: Platform.OS === 'android' ? 19 : Typography.fontSize.h1,
    lineHeight: Platform.OS === 'android' ? 26 : Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
  },
  stepDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Platform.OS === 'android' ? 15 : Typography.fontSize.body,
    lineHeight: Platform.OS === 'android' ? 22 : Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    width: '100%',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? 0 : Spacing.modal.footerPadding,
    paddingBottom: Spacing.modal.footerPadding,
    paddingHorizontal: Spacing.modal.footerPaddingHorizontal,
    gap: Spacing.modal.footerGap,
    backgroundColor: colors.cardBackground,
    width: '100%',
  },
  progressContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.progressBarGap,
  },
  progressBar: {
    flex: 1,
    height: Spacing.modal.progressBarHeight,
    borderRadius: Spacing.modal.progressBarRadius,
  },
  progressBarActive: {
    backgroundColor: colors.progressActive,
  },
  progressBarInactive: {
    backgroundColor: colors.progressInactive,
  },
  arrowButton: {
    width: Spacing.modal.arrowButtonSize,
    height: Spacing.modal.arrowButtonSize,
    borderRadius: Spacing.modal.arrowButtonRadius,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

// Android's mediaContainer is 120h with paddingBottom: 20, giving ~100px of
// inner space — smaller than the shared 225 stepVideoSize. With
// `resizeMode: contain` the overflow would shift the visible image content,
// so every slide is clamped to the same square footprint on Android.
const ANDROID_SLIDE_IMAGE = 100;

export const createStepSpecificStyles = (colors: ReturnType<typeof useColors>) => StyleSheet.create({
  stepIntroConsentVideo: {
    width: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.stepVideoSize,
    height: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.stepVideoSize,
  },
  stepEligibilityCheckImage: {
    width: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.stepVideoSize,
    height: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.stepVideoSize,
  },
  stepAnonymousVoteExplainerImage: {
    width: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.stepVideoSize,
    height: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.stepVideoSize,
  },
  // StepIntroVideo — teaching clip shown before the user reaches
  // StepDocumentScanStart's "Démarrer l'analyse" content. The video fills
  // the available vertical space; the skip button sits below it, hugging
  // the bottom of the modal sheet.
  stepIntroContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.cardBackground,
    justifyContent: 'space-between',
  },
  stepIntroVideo: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepIntroSkipButton: {
    paddingVertical: 16,
    marginHorizontal: 24,
    marginBottom: 24,
    backgroundColor: colors.secondary,
    alignItems: 'center',
  },
  stepIntroSkipButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepDocumentScanStartContainer: {
    padding: Spacing.modal.stepDocumentScanStartPadding,
    paddingBottom: 40,
    gap: Spacing.modal.stepDocumentScanStartGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepDocumentScanStartContent: {
    gap: Spacing.modal.stepDocumentScanStartContentGap,
    alignItems: 'flex-start',
    width: '100%',
  },
  stepDocumentScanStartTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepDocumentScanStartVideo: {
    width: Spacing.modal.stepVideoSize,
    height: Spacing.modal.stepVideoSize,
  },
  stepDocumentScanStartButton: {
    paddingVertical: Spacing.modal.stepDocumentScanStartButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  stepDocumentScanStartButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepMRZScanContainer: {
    paddingTop: Spacing.modal.stepMRZScanPadding,
    paddingBottom: 32,
    paddingHorizontal: 0,
    gap: 16,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepMRZScanTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepMRZScanCamera: {
    width: '100%',
    height: Spacing.modal.stepMRZScanCameraHeight,
    overflow: 'visible',
  },
  stepMRZScanCameraOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepMRZScanScanArea: {
    width: '80%',
    height: 80,
    justifyContent: 'flex-end',
    paddingBottom: 8,
  },
  stepMRZScanInstructionContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
  },
  stepMRZScanCornerTopLeft: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  stepMRZScanCornerTopRight: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  stepMRZScanCornerBottomLeft: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  stepMRZScanCornerBottomRight: {
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  stepMRZScanMrzContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 2,
  },
  stepMRZScanMrzText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 10,
    fontWeight: '700',
    color: colors.buttonText,
    letterSpacing: 0.5,
    opacity: 1,
  },
  stepMRZScanInstructionText: {
    fontFamily: Typography.fontFamily.medium,
    fontSize: Typography.fontSize.body,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepMRZScanButton: {
    paddingVertical: 16,
    marginHorizontal: 24,
    marginBottom: 16,
    backgroundColor: colors.cardBackground,
    borderRadius: 8,
    alignItems: 'center',
    width: 'auto',
  },
  stepMRZScanButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.text,
    textAlign: 'center',
  },
  stepNFCReadContainer: {
    paddingVertical: Spacing.modal.stepNFCReadPadding,
    paddingHorizontal: 0,
    gap: Spacing.modal.stepNFCReadGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepNFCReadTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepNFCReadImageContainer: {
    width: '100%',
    alignItems: 'center',
  },
  stepNFCReadImage: {
    width: Spacing.modal.stepVideoSize,
    height: Spacing.modal.stepVideoSize,
    backgroundColor: colors.cardBackground,
  },
  stepNFCReadButtonContainer: {
    paddingHorizontal: Spacing.modal.stepNFCReadButtonPaddingHorizontal,
    width: '100%',
  },
  stepNFCReadButton: {
    paddingVertical: Spacing.modal.stepNFCReadButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  stepNFCReadButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepBlockchainVerifyContainer: {
    padding: Spacing.modal.stepBlockchainVerifyPadding,
    gap: Spacing.modal.stepBlockchainVerifyGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepBlockchainVerifyTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepBlockchainVerifyImage: {
    width: Spacing.modal.stepVideoSize,
    height: Spacing.modal.stepVideoSize,
  },
  stepBlockchainVerifyDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.body,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepReadyToVoteContainer: {
    padding: Spacing.modal.stepReadyToVotePadding,
    gap: Spacing.modal.stepReadyToVoteGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepReadyToVoteContent: {
    gap: Spacing.modal.stepReadyToVoteContentGap,
    alignItems: 'center',
    width: '100%',
  },
  stepReadyToVoteTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepReadyToVoteSuccessAnimation: {
    width: Spacing.modal.stepReadyToVoteSuccessSize,
    height: Spacing.modal.stepReadyToVoteSuccessSize,
  },
  stepReadyToVoteButton: {
    paddingVertical: Spacing.modal.stepReadyToVoteButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  stepReadyToVoteButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepVoteChoiceContainer: {
    padding: 24,
    gap: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepVoteChoiceConfirmationCard: {
    padding: 32,
    gap: 24,
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 24,
  },
  stepVoteChoiceTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 24,
    lineHeight: 31,
    letterSpacing: 0.24,
    color: colors.secondary,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteChoiceImage: {
    width: 175,
    height: 175,
  },
  stepVoteChoiceButtonRow: {
    flexDirection: 'row',
    gap: 24,
    width: '100%',
  },
  stepVoteChoiceCancelButton: {
    flex: 1,
    paddingVertical: 14,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepVoteChoiceCancelButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0.4,
    color: colors.secondary,
    textAlign: 'center',
  },
  stepVoteChoiceConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepVoteChoiceConfirmButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0.4,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepVoteChoiceOptionsContainer: {
    flexDirection: 'column',
    gap: 16,
    width: '100%',
  },
  stepVoteChoiceOptionButton: {
    paddingVertical: 16,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  stepVoteChoiceOptionButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0.4,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepVoteChoiceCancelButtonFullWidth: {
    paddingVertical: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  stepVoteChoiceErrorContainer: {
    padding: Spacing.modal.stepVoteChoiceErrorPadding,
    gap: Spacing.modal.stepVoteChoiceErrorGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepVoteChoiceErrorContent: {
    gap: Spacing.modal.stepVoteChoiceErrorContentGap,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteChoiceErrorTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteChoiceErrorDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteChoiceErrorAnimation: {
    width: Spacing.modal.stepVoteChoiceErrorAnimationSize,
    height: Spacing.modal.stepVoteChoiceErrorAnimationSize,
  },
  stepVoteChoiceErrorButton: {
    paddingVertical: Spacing.modal.stepVoteChoiceErrorButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteChoiceErrorButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepVoteConfirmContainer: {
    padding: Spacing.modal.stepVoteConfirmPadding,
    gap: Spacing.modal.stepVoteConfirmGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepVoteConfirmContent: {
    gap: Spacing.modal.stepVoteConfirmContentGap,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteConfirmTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteConfirmBallotVideo: {
    width: Spacing.modal.stepVideoSize,
    height: Spacing.modal.stepVideoSize,
  },
  stepVoteConfirmButtonContainer: {
    flexDirection: 'row',
    gap: Spacing.modal.stepVoteConfirmButtonGap,
    width: '100%',
  },
  stepVoteConfirmCancelButton: {
    flex: 1,
    paddingVertical: Spacing.modal.stepVoteConfirmButtonPaddingVertical,
    backgroundColor: colors.cardBackground,
    alignItems: 'center',
  },
  stepVoteConfirmCancelButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.text,
    textAlign: 'center',
  },
  stepVoteConfirmConfirmButton: {
    flex: 1,
    paddingVertical: Spacing.modal.stepVoteConfirmButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
  },
  stepVoteConfirmConfirmButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepProofSubmissionContainer: {
    flex: 1,
    padding: Spacing.modal.stepProofSubmissionPadding,
    gap: Spacing.modal.stepProofSubmissionGap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepProofSubmissionLoading: {
    width: Spacing.modal.stepProofSubmissionLoadingWidth,
    height: Spacing.modal.stepProofSubmissionLoadingHeight,
  },
  stepVoteSuccessContainer: {
    flex: 1,
    padding: Spacing.modal.stepVoteSuccessPadding,
    gap: Spacing.modal.stepVoteSuccessGap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepVoteSuccessContent: {
    gap: Spacing.modal.stepVoteSuccessContentGap,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteSuccessTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteSuccessDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteSuccessAnimation: {
    width: Spacing.modal.stepVoteSuccessAnimationSize,
    height: Spacing.modal.stepVoteSuccessAnimationSize,
  },
  stepVoteSuccessButton: {
    paddingVertical: Spacing.modal.stepVoteSuccessButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteSuccessButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  stepVoteErrorContainer: {
    flex: 1,
    padding: Spacing.modal.stepVoteErrorPadding,
    gap: Spacing.modal.stepVoteErrorGap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepVoteErrorContent: {
    gap: Spacing.modal.stepVoteErrorContentGap,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteErrorTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteErrorDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  stepVoteErrorAnimation: {
    width: Spacing.modal.stepVoteErrorAnimationSize,
    height: Spacing.modal.stepVoteErrorAnimationSize,
  },
  stepVoteErrorButton: {
    paddingVertical: Spacing.modal.stepVoteErrorButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  stepVoteErrorButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
});