import { Spacing, Typography, useColors } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';

export const createModalStyles = (colors: ReturnType<typeof useColors>) => StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
  },
  titleSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: Spacing.modal.titlePadding,
    paddingHorizontal: Spacing.modal.titlePaddingHorizontal,
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  title: {
    flex: 1,
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
  },
  slidingWrapper: {
    overflow: 'hidden',
    alignSelf: 'stretch',
    // On Android, fill the available vertical space above the nav bar so the
    // white slide background extends consistently across steps 1–3 (otherwise
    // the row shrinks to the tallest mounted slide, which differs per step
    // because of the ±1 mount window — Step 4 is taller than Steps 1–3).
    flex: Platform.OS === 'android' ? 1 : undefined,
  },
  slidingContainer: {
    flexDirection: 'row',
    // Fill slidingWrapper's height on Android so row-children (slides) stretch
    // vertically to the full available space. Without this, the row shrinks to
    // max(slide intrinsic heights) and the white slide backgrounds end at
    // different Y positions between steps.
    flex: Platform.OS === 'android' ? 1 : undefined,
  },
  stepSlide: {
    alignItems: 'center',
    backgroundColor: Platform.OS === 'android' ? colors.cardBackground : undefined,
  },
  mediaContainer: {
    height: Platform.OS === 'android' ? 120 : Spacing.modal.mediaContainerHeight,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.cardBackground,
    width: '100%',
    paddingBottom: Platform.OS === 'android' ? 20 : 0,
  },
  contentSection: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    paddingTop: Platform.OS === 'android' ? Spacing.l : Spacing.l,
    paddingBottom: Platform.OS === 'android' ? 0 : Spacing.l,
    paddingHorizontal: Spacing.modal.contentPaddingHorizontal,
    gap: Platform.OS === 'android' ? 0 : Spacing.modal.contentGap,
    backgroundColor: colors.cardBackground,
    width: '100%',
    height: Platform.OS === 'android' ? 'auto' : 'auto',
  },
  stepContent: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: Platform.OS === 'android' ? Spacing.s : Spacing.modal.stepTitleGap,
    width: '100%',
  },
  stepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.stepTitleGap,
    width: '100%',
  },
  numberCircle: {
    width: Spacing.modal.numberCircleSize,
    height: Spacing.modal.numberCircleSize,
    borderRadius: Spacing.modal.numberCircleSize / 2,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  numberText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.body,
    color: colors.buttonText,
  },
  stepTitle: {
    flex: 1,
    fontFamily: Typography.fontFamily.bold,
    fontSize: Platform.OS === 'android' ? 19 : Typography.fontSize.h1,
    lineHeight: Platform.OS === 'android' ? 26 : Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
  },
  stepDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Platform.OS === 'android' ? 15 : Typography.fontSize.body,
    lineHeight: Platform.OS === 'android' ? 22 : Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    width: '100%',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? 0 : Spacing.modal.footerPadding,
    paddingBottom: Spacing.modal.footerPadding,
    paddingHorizontal: Spacing.modal.footerPaddingHorizontal,
    gap: Spacing.modal.footerGap,
    backgroundColor: colors.cardBackground,
    width: '100%',
  },
  progressContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.modal.progressBarGap,
  },
  progressBar: {
    flex: 1,
    height: Spacing.modal.progressBarHeight,
    borderRadius: Spacing.modal.progressBarRadius,
  },
  progressBarActive: {
    backgroundColor: colors.progressActive,
  },
  progressBarInactive: {
    backgroundColor: colors.progressInactive,
  },
  arrowButton: {
    width: Spacing.modal.arrowButtonSize,
    height: Spacing.modal.arrowButtonSize,
    borderRadius: Spacing.modal.arrowButtonRadius,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

// Android's mediaContainer is 120h with paddingBottom: 20, giving ~100px of
// inner space. The iOS-sized assets (167–175h) overflow that container; with
// `resizeMode: contain` the overflow shifts the visible image content and makes
// the three slides look misaligned (ballot sits visibly lower than card/phone).
// Clamp all three to the same footprint on Android so they line up identically.
const ANDROID_SLIDE_IMAGE = 100;
const ANDROID_CARD_WIDTH = Math.round(ANDROID_SLIDE_IMAGE * (199 / 167)); // keep card aspect

export const createStepSpecificStyles = (colors: ReturnType<typeof useColors>) => StyleSheet.create({
  cardVideo: {
    width: Platform.OS === 'android' ? ANDROID_CARD_WIDTH : Spacing.modal.cardImageWidth,
    height: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.cardImageHeight,
  },
  phoneImage: {
    width: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.phoneImageSize,
    height: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.phoneImageSize,
  },
  ballotImage: {
    width: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.ballotImageSize,
    height: Platform.OS === 'android' ? ANDROID_SLIDE_IMAGE : Spacing.modal.ballotImageSize,
  },
  // StepIntroVideo — teaching clip shown before the user reaches
  // StepDocumentScanStart's "Démarrer l'analyse" content. The video fills
  // the available vertical space; the skip button sits below it, hugging
  // the bottom of the modal sheet.
  stepIntroContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.cardBackground,
    justifyContent: 'space-between',
  },
  stepIntroVideo: {
    flex: 1,
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  stepIntroSkipButton: {
    paddingVertical: 16,
    marginHorizontal: 24,
    marginBottom: 24,
    backgroundColor: colors.secondary,
    alignItems: 'center',
  },
  stepIntroSkipButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step4Container: {
    padding: Spacing.modal.step4Padding,
    paddingBottom: 40,
    gap: Spacing.modal.step4Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step4Content: {
    gap: Spacing.modal.step4ContentGap,
    alignItems: 'flex-start',
    width: '100%',
  },
  step4Title: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step4Video: {
    width: Spacing.modal.cardImageWidth,
    height: Spacing.modal.cardImageHeight,
  },
  step4Button: {
    paddingVertical: Spacing.modal.step4ButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step4ButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step5Container: {
    paddingTop: Spacing.modal.step5Padding,
    paddingBottom: 32,
    paddingHorizontal: 0,
    gap: 16,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step5Title: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step5Camera: {
    width: '100%',
    height: Spacing.modal.step5CameraHeight,
    overflow: 'visible',
  },
  step5CameraOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  step5ScanArea: {
    width: '80%',
    height: 80,
    justifyContent: 'flex-end',
    paddingBottom: 8,
  },
  step5InstructionContainer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
  },
  step5CornerTopLeft: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  step5CornerTopRight: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  step5CornerBottomLeft: {
    position: 'absolute',
    bottom: 0,
    left: 0,
  },
  step5CornerBottomRight: {
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  step5MrzContainer: {
    width: '100%',
    alignItems: 'center',
    gap: 2,
  },
  step5MrzText: {
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
    fontSize: 10,
    fontWeight: '700',
    color: colors.buttonText,
    letterSpacing: 0.5,
    opacity: 1,
  },
  step5InstructionText: {
    fontFamily: Typography.fontFamily.medium,
    fontSize: Typography.fontSize.body,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step5Button: {
    paddingVertical: 16,
    marginHorizontal: 24,
    marginBottom: 16,
    backgroundColor: colors.cardBackground,
    borderRadius: 8,
    alignItems: 'center',
    width: 'auto',
  },
  step5ButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.text,
    textAlign: 'center',
  },
  step6Container: {
    paddingVertical: Spacing.modal.step6Padding,
    paddingHorizontal: 0,
    gap: Spacing.modal.step6Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step6Title: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step6ImageContainer: {
    width: '100%',
    alignItems: 'center',
  },
  step6Image: {
    width: Spacing.modal.step6ImageWidth,
    height: Spacing.modal.step6ImageHeight,
    backgroundColor: colors.cardBackground,
  },
  step6ButtonContainer: {
    paddingHorizontal: Spacing.modal.step6ButtonPaddingHorizontal,
    width: '100%',
  },
  step6Button: {
    paddingVertical: Spacing.modal.step6ButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step6ButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step7Container: {
    padding: Spacing.modal.step7Padding,
    gap: Spacing.modal.step7Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step7Title: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.settingRow,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step7Image: {
    width: Spacing.modal.step7ImageSize,
    height: Spacing.modal.step7ImageSize,
  },
  step7Description: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.body,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step8Container: {
    padding: Spacing.modal.step8Padding,
    gap: Spacing.modal.step8Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step8Content: {
    gap: Spacing.modal.step8ContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step8Title: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step8SuccessAnimation: {
    width: Spacing.modal.step8SuccessSize,
    height: Spacing.modal.step8SuccessSize,
  },
  step8Button: {
    paddingVertical: Spacing.modal.step8ButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step8ButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step9VoteContainer: {
    padding: 24,
    gap: 16,
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step9VoteConfirmationCard: {
    padding: 32,
    gap: 24,
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 24,
  },
  step9VoteTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 24,
    lineHeight: 31,
    letterSpacing: 0.24,
    color: colors.secondary,
    textAlign: 'center',
    width: '100%',
  },
  step9VoteImage: {
    width: 175,
    height: 175,
  },
  step9VoteButtonRow: {
    flexDirection: 'row',
    gap: 24,
    width: '100%',
  },
  step9VoteCancelButton: {
    flex: 1,
    paddingVertical: 14,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  step9VoteCancelButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0.4,
    color: colors.secondary,
    textAlign: 'center',
  },
  step9VoteConfirmButton: {
    flex: 1,
    paddingVertical: 14,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  step9VoteConfirmButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0.4,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step9VoteOptionsContainer: {
    flexDirection: 'column',
    gap: 16,
    width: '100%',
  },
  step9VoteOptionButton: {
    paddingVertical: 16,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  step9VoteOptionButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: 20,
    lineHeight: 26,
    letterSpacing: 0.4,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step9VoteCancelButtonFullWidth: {
    paddingVertical: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  step9ErrorContainer: {
    padding: Spacing.modal.step9ErrorPadding,
    gap: Spacing.modal.step9ErrorGap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step9ErrorContent: {
    gap: Spacing.modal.step9ErrorContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step9ErrorTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step9ErrorDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step9ErrorAnimation: {
    width: Spacing.modal.step9ErrorAnimationSize,
    height: Spacing.modal.step9ErrorAnimationSize,
  },
  step9ErrorButton: {
    paddingVertical: Spacing.modal.step9ErrorButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step9ErrorButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step10Container: {
    padding: Spacing.modal.step10Padding,
    gap: Spacing.modal.step10Gap,
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step10Content: {
    gap: Spacing.modal.step10ContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step10Title: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step10BallotVideo: {
    width: Spacing.modal.step10BallotSize,
    height: Spacing.modal.step10BallotSize,
  },
  step10ButtonContainer: {
    flexDirection: 'row',
    gap: Spacing.modal.step10ButtonGap,
    width: '100%',
  },
  step10CancelButton: {
    flex: 1,
    paddingVertical: Spacing.modal.step10ButtonPaddingVertical,
    backgroundColor: colors.cardBackground,
    alignItems: 'center',
  },
  step10CancelButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.text,
    textAlign: 'center',
  },
  step10ConfirmButton: {
    flex: 1,
    paddingVertical: Spacing.modal.step10ButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
  },
  step10ConfirmButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step11Container: {
    flex: 1,
    padding: Spacing.modal.step11Padding,
    gap: Spacing.modal.step11Gap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step11Loading: {
    width: Spacing.modal.step11LoadingWidth,
    height: Spacing.modal.step11LoadingHeight,
  },
  step12SuccessContainer: {
    flex: 1,
    padding: Spacing.modal.step12SuccessPadding,
    gap: Spacing.modal.step12SuccessGap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step12SuccessContent: {
    gap: Spacing.modal.step12SuccessContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step12SuccessTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step12SuccessDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step12SuccessAnimation: {
    width: Spacing.modal.step12SuccessAnimationSize,
    height: Spacing.modal.step12SuccessAnimationSize,
  },
  step12SuccessButton: {
    paddingVertical: Spacing.modal.step12SuccessButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step12SuccessButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
  step12ErrorContainer: {
    flex: 1,
    padding: Spacing.modal.step12ErrorPadding,
    gap: Spacing.modal.step12ErrorGap,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    backgroundColor: colors.cardBackground,
  },
  step12ErrorContent: {
    gap: Spacing.modal.step12ErrorContentGap,
    alignItems: 'center',
    width: '100%',
  },
  step12ErrorTitle: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.h1,
    lineHeight: Typography.lineHeight.h1,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step12ErrorDescription: {
    fontFamily: Typography.fontFamily.medium,
    fontWeight: Typography.fontWeight.medium,
    fontSize: Typography.fontSize.body,
    lineHeight: Typography.lineHeight.body,
    letterSpacing: Typography.letterSpacing.h1,
    color: colors.text,
    textAlign: 'center',
    width: '100%',
  },
  step12ErrorAnimation: {
    width: Spacing.modal.step12ErrorAnimationSize,
    height: Spacing.modal.step12ErrorAnimationSize,
  },
  step12ErrorButton: {
    paddingVertical: Spacing.modal.step12ErrorButtonPaddingVertical,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    width: '100%',
  },
  step12ErrorButtonText: {
    fontFamily: Typography.fontFamily.bold,
    fontSize: Typography.fontSize.button,
    lineHeight: Typography.lineHeight.button,
    letterSpacing: Typography.letterSpacing.button,
    color: colors.buttonText,
    textAlign: 'center',
  },
});